[phases.setup]
nixPkgs = ['python312', 'gcc', 'nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['pip install -r requirements.txt', 'cd frontend && npm install']

[phases.build]
cmds = ['cd frontend && npm run build', 'python manage.py migrate --noinput', 'python manage.py collectstatic --noinput']

[start]
cmd = 'gunicorn djangoproj.wsgi --log-file -'
